plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/PredicatePrefix:
  NamePrefix: 
    - is_
  ForbiddenPrefixes:
    - is_

Naming/PredicateMethod:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: false

RSpec/IncludeExamples:
  Enabled: false
